Repository vcvedika/Basic-Calculator, pull requests merged in 2022-10, with the labels that each got.

#1 added inverse trignometric functionality
  index.html
  main.js
Labels: hactoberfest-accepted

#4 Arcsin
  index.html
  main.js
Labels: hacktoberfest-accepted

#5 arccos
  index.html
  main.js
Labels: hacktoberfest-accepted

#6 arctan
  index.html
  main.js
Labels: hacktoberfest-accepted

#7 adding hyperbolic-function and add same css to the remaining buttons …
  index.html
  main.js
  style.css
Labels: hacktoberfest-accepted

#8 Second
  main.js
Labels: hacktoberfest

#12 Third
  main.js
Labels: hacktoberfest
